yarnPath: .yarn/releases/yarn-3.4.1.cjs

packageExtensions:
  "@sapphire/framework@*":
    dependencies:
      "discord-api-types": '*'
  "@sapphire/decorators@*":
    dependencies:
      "@sapphire/discord.js-utilities": "*"
