compressionLevel: mixed

enableGlobalCache: false

nodeLinker: pnpm

packageExtensions:
  "@sapphire/decorators@*":
    dependencies:
      "@sapphire/discord.js-utilities": "*"
  "@sapphire/framework@*":
    dependencies:
      discord-api-types: "*"
  "@sapphire/plugin-editable-commands@*":
    dependencies:
      "@sapphire/pieces": "*"
  "@sapphire/plugin-subcommands@*":
    dependencies:
      "@sapphire/pieces": "*"
      "@sapphire/ratelimits": "*"

yarnPath: .yarn/releases/yarn-4.1.1.cjs
